ARTIFACTS:
  ARTIFACTS_DIR: artifacts
  VECTORIZER: TfidfVectorizer.pkl
  TRAINED_MODEL:  LogisticRegression.pkl

DATABASE:
  CASSANDRA_FILE_PATH: config/secure-connect-sentiment-analyzer.zip
  CLIENTID: ###
  CLIENTSECRET: ###